services:
  - type: web
    name: uwleo
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
